[package]
name = "twitch-send"
version = "0.1.0"
authors = ["hardliner66 <hardliner66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch_chat_wrapper = { git = "https://github.com/hardliner66/twitch_chat_wrapper", branch = "eof_crash_workaround" }
